### ISSUE TITLE
Error when using app_install.py

### ISSUE THREAD

**Issue by ghost** [xomachine/SteamForwarder#10]
I am using Ubuntu 16.04.3 LTS.  When I run:

python3 app_install.py --wineprefix ~/steamWindowsPrefix/ --login ********* --password ********** 730

I get this python error:

Traceback (most recent call last):
  File "app_install.py", line 159, in <module>
    aparser.add_argument('-s', '--steamapps-dir', help='path to the steamapps dir', type=str, dest='steamapps', default=config["steamapps"])
KeyError: 'steamapps'

**Comment by xomachine** [comment]
It looks like you are using an outdated script. Just download the [latest one](https://github.com/xomachine/SteamForwarder/blob/master/app_install.py).
Also I recommend to set steamapps directory manually (in config or via using --store and --steamapps-dir) because the script may fail to detect it automatically.

Release will be updated soon...
